// Generated by Wrangler by running `wrangler types`

interface Env {
	WORKFLOW_EXAMPLES: KVNamespace;
	WITH_RETRY_WORKFLOW: Workflow;
	PAYMENT_PROVIDER_A_WORKFLOW: Workflow;
	PAYMENT_PROVIDER_B_WORKFLOW: Workflow;
	PAYMENT_BATCH_WORKFLOW: Workflow;
}
